global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node-exporters
    static_configs:
      - targets:
          - 10.0.1.177:9100 # wg-gateway
          - 10.0.1.67:9100 # runner-ci
          - 10.10.10.10:9100 # k3s-master
          - 10.10.10.11:9100 # k3s-worker
          - 10.10.10.12:9100 # infra
